server:
  port: 8080


spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            ace-application:
              - uri: http://localhost:8999
#                metadata:
#                  management.context-path: /actuator
              - uri: http://localhost:8088
#                metadata:
#                  management.context-path: /actuator
  thymeleaf:
    check-template-location: false
    cache: false
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: root
        password: root
  application:
    name: Spring Boot 2 Admin Server

management:
  endpoints:
    web:
      exposure:
        include: '*'


#??console log ????
logging:
  charset:
    console: UTF-8
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS,GMT+8} %highlight(%-5level) [%boldMagenta(%-10t)]- %green(%c) %boldCyan(%-10M): %msg%n"
